spring:
  application:
    name: BackAngularT

  datasource:
    url: jdbc:postgresql://prod-url:5432/roupasdb
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
